server {
    listen ${NGINX_PORT};
    resolver 127.0.0.11;
    location /graphql {
        auth_request /auth;
        proxy_pass http://${GRAPH_QL_HOSTNAME}:${GRAPH_QL_PORT};
    }
    location = /login.html {
        root ${NGINX_FOLDER};
        index login.html;
    }
    location = /login.js {
        root ${NGINX_FOLDER};
        index login.js;
    }
    location / {
        auth_request /auth;
        error_page 401 = /login.html;
        error_page 403 = /login.html;

        root ${NGINX_FOLDER};
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline';" always;
        index doc.html;
    }
    location /login {
        proxy_pass http://${GRAPH_QL_HOSTNAME}:${GRAPH_QL_AUTH_PORT};
    }
    location /auth {
        proxy_pass http://${GRAPH_QL_HOSTNAME}:${GRAPH_QL_AUTH_PORT};
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }
}