server {
    listen ${NGINX_PORT};
    location /graphql {
        proxy_pass http://gql:4000;
        # Add CORS headers here if needed
    }
    location / {
        root ${NGINX_FOLDER};
        index index.html;
    }

}