server {
    listen ${NGINX_PORT};
    location ~ ^/(graphql|login)$ {
        proxy_pass http://${GRAPH_QL_HOSTNAME}:${GRAPH_QL_PORT};
        resolver 127.0.0.11;
    }
    location / {
        root ${NGINX_FOLDER};
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline';" always;
        index index.html;
    }
}