
volumes:
  build_folder:
    external: true

services:
  node_app:
      image: my-backend
      volumes:
        - ./tsconfig.json:${WORKDIR}/tsconfig.json
        - ./healthcheck.js:${WORKDIR}/healthcheck.js
        - build_folder:${WORKDIR}/build
        - ./${COMMON_DIR_NAME}:${WORKDIR}/${COMMON_DIR_NAME}
        - ./package.json:${WORKDIR}/package.json
        - ${LOG_MOUNT_HOST}:${LOG_MOUNT}
      working_dir: ${WORKDIR}
      entrypoint: ["/bin/bash", "-c"]
      command: ["npm run buildrun; exec bash"]
      env_file:
        - ./.env
      environment:
        - NODE_PRESERVE_SYMLINKS=1
        - HEALTHCHECK_PORT=${HEALTHCHECK_PORT}
        - LOGGING=info
        - LOG_MOUNT=${LOG_MOUNT}
      tty: true
      stdin_open: true
      mem_limit: 3g
      memswap_limit: 0m
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "node ./healthcheck.js ${HEALTHCHECK_PORT} >> ./healthcheck.log"]
        interval: 20s
        timeout: 10s
        retries: 3
        start_period: 40s
        start_interval: 1s 
