services:
  node_img_builder:
    build:
      dockerfile_inline: |
        FROM node:24-slim
        WORKDIR ${WORKDIR}
        COPY ./package.json ${WORKDIR}/package.json
        RUN apt update; apt install -y procps net-tools iputils-ping curl wget apache2-utils; npm install
    image: my-backend

  docs:
    image: my-backend
    container_name: docs
    volumes:
      - /tmpz/tmp/docsite:${SOURCEDIR}
      - ./frontend/docsite:${SOURCEDIR}/docsite
      - ./frontend/docs/umls:${SOURCEDIR}/docsite/static/umls
      - /tmpz/tmp/docsite/node_modules:${SOURCEDIR}/docsite/node_modules
    tty: true
    stdin_open: true
    environment:
      - DOCS_PORT=${DOCS_PORT}
    ports:
      - "127.0.0.1:${DOCS_PORT}:3000"
