networks:
  backend_net:
    driver: bridge
    name: backend_net


volumes:
  frontend_deploy_folder:
  shared_dir:

x-gql-env: &gql_env
  GRAPH_QL_PORT: ${GRAPH_QL_PORT}
  GRAPH_QL_HOSTNAME: ${GRAPH_QL_APP_NAME}

x-environment: &mssql_env
  MSSQL_HOSTNAME: ${MSSQL_HOSTNAME}
  MSSQL_SA_USERNAME: ${MSSQL_SA_USERNAME}
  MSSQL_PASSWORD: ${MSSQL_PASSWORD}
  MSSQL_DB_NAME: ${MSSQL_DB_NAME}
  MSSQL_CONSUMER_USERNAME: ${MSSQL_CONSUMER_USERNAME}
  MSSQL_STATEMENT_CREATOR_USERNAME: ${MSSQL_STATEMENT_CREATOR_USERNAME}

x-healthcheck-params: &healthcheck_params
  interval: 20s
  timeout: 10s
  retries: 3
  start_period: 40s
  start_interval: 1s


# Environment variables are read from .env file automatically
services:
  node_img_builder:
    build:
      dockerfile_inline: |
        FROM node:24-slim
        VOLUME [${WORKDIR}]
        WORKDIR ${WORKDIR}
        COPY ./package.json ${WORKDIR}/package.json
        RUN apt update; apt install -y procps net-tools iputils-ping curl wget apache2-utils; npm install; rm package*.json
    image: my-backend
  frontend_builder:
      extends:
        file: base_services.yaml
        service: node_app
      environment:
        - FRONTEND_DEPLOY_FOLDER=${FRONTEND_DEPLOY_FOLDER}
      volumes:
        - ./${FRONTEND_NAME}:${SOURCEDIR}
        - frontend_deploy_folder:${FRONTEND_DEPLOY_FOLDER}
        - ./${COMMON_DIR_NAME}/event_types.ts:${WORKDIR}/${COMMON_DIR_NAME}/event_types.ts
        - ./${COMMON_DIR_NAME}/generator_parameters.ts:${WORKDIR}/${COMMON_DIR_NAME}/generator_parameters.ts
        - ./${COMMON_DIR_NAME}/gqlDeclarations.ts:${WORKDIR}/${COMMON_DIR_NAME}/gqlDeclarations.ts
      container_name: frontend_builder
      # restart: no
      # tty: false
      # stdin_open: false

  frontend_server:
    image: nginx:mainline-alpine3.22
    container_name: frontend_server
    dns_search: backend_net
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: ${NGINX_TEMPLATE_FOLDER}
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
      NGINX_PORT: ${NGINX_PORT}
      NGINX_FOLDER: ${NGINX_FOLDER}
      <<: [*gql_env]
    volumes:
    - frontend_deploy_folder:/${NGINX_FOLDER}
    - shared_dir:${SHARED_DIR}
    - ./${FRONTEND_NAME}/f.conf:${NGINX_TEMPLATE_FOLDER}/f.conf.template
    ports:
    - "127.0.0.1:81:81"
    # depends_on:
    #   frontend_builder:
    #     condition: service_completed_successfully
    #   gql:
    #     condition: service_healthy
    networks:
      - backend_net

  gql:
      extends:
        file: base_services.yaml
        service: node_monitored_app
      volumes:
        - ./${GRAPH_QL_APP_NAME}:${SOURCEDIR}
        - ./${COMMON_DIR_NAME}/event_types.ts:${WORKDIR}/${COMMON_DIR_NAME}/event_types.ts
        - ./${COMMON_DIR_NAME}/generator_parameters.ts:${WORKDIR}/${COMMON_DIR_NAME}/generator_parameters.ts
        - ./${COMMON_DIR_NAME}/gqlDeclarations.ts:${WORKDIR}/${COMMON_DIR_NAME}/gqlDeclarations.ts
        - ./${COMMON_DIR_NAME}/apiRequestHandler.ts:${WORKDIR}/${COMMON_DIR_NAME}/apiRequestHandler.ts
      container_name: "${GRAPH_QL_APP_NAME}"
      hostname: "${GRAPH_QL_APP_NAME}"
      environment:
        - GENERATOR_PORT=${GENERATOR_PORT}
        - GENERATOR_HOST=${GENERATOR_NAME}
        - STATEMENT_GENERATOR_PORT=${STATEMENT_GENERATOR_PORT}
        - STATEMENT_GENERATOR_HOST=${STATEMENT_GENERATOR_NAME}
        - GRAPH_QL_PORT=${GRAPH_QL_PORT}
      depends_on:
        generator:
          condition: service_healthy
        statement_generator:
          condition: service_healthy

  generator:
      extends:
        file: base_services.yaml
        service: node_kafka_app
      volumes:
        - ./${GENERATOR_NAME}:${SOURCEDIR}
        - shared_dir:${SHARED_DIR}
        - ./${COMMON_DIR_NAME}/apiRequestHandler.ts:${WORKDIR}/${COMMON_DIR_NAME}/apiRequestHandler.ts

      hostname: "${GENERATOR_NAME}"
      environment:
        - GENERATOR_PORT=${GENERATOR_PORT}
        - SHARED_DIR=${SHARED_DIR}
      depends_on:
        kafka1:
          condition: service_started


  prometheus:
    image: prom/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./${PROMETHEUS_NAME}:${SOURCEDIR}
    hostname: "${PROMETHEUS_NAME}"
    environment:
      - GRAPH_QL_APP_NAME=${GRAPH_QL_APP_NAME}
      - GENERATOR_NAME=${GENERATOR_NAME}
      - MONITORING_PORT=${MONITORING_PORT}
      - MESSAGE_SINK_NAME=${MESSAGE_SINK_NAME}
      - STATEMENT_GENERATOR_NAME=${STATEMENT_GENERATOR_NAME}
    entrypoint: ["sh", "-c"]
    tty: true
    command: ['${SOURCEDIR}/generateConfig.sh > /etc/prometheus/prometheus.yml;
              prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus;
              exec sh']
    networks:
      - backend_net

  graphana:
    image: grafana/grafana:11.6.3
    hostname: "${GRAPHANA_NAME}"
    volumes:
      -  /${GRAPHANA_DASHBOARD_FOLDER}
      - ./${GRAPHANA_NAME}/datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./${GRAPHANA_NAME}/grafana.ini:/etc/grafana/grafana.ini
      - ./${GRAPHANA_NAME}/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./${GRAPHANA_NAME}/dash1.json:/${GRAPHANA_DASHBOARD_FOLDER}/dash1.json
    environment:
      - PROMETHEUS_HOST=${PROMETHEUS_NAME}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - GRAPHANA_DASHBOARD_FOLDER=${GRAPHANA_DASHBOARD_FOLDER}
    ports:
      - "127.0.0.1:${GRAPHANA_PORT_HOST}:3000"
    networks:
      - backend_net

  kafka1:
    extends:
      file: base_services.yaml
      service: kafka-app
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${KAFKA_HOST}:9092'
    hostname: "${KAFKA_HOST}"

  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - "${WORKDIR}"
    working_dir: ${WORKDIR}
    # Uncomment ports to connect to the database from outside
    ports:
    - "127.0.0.1:1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    hostname: "${MSSQL_HOSTNAME}"
    mem_limit: 5g
    memswap_limit: 0m
    networks:
        - backend_net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd  -S localhost -U ${MSSQL_CONSUMER_USERNAME} -P ${MSSQL_PASSWORD} -C -Q exit"]
      <<: [*healthcheck_params]


  db_initializer:
      extends:
        file: base_services.yaml
        service: node_app
      volumes:
        - ./${DB_INITIALIZER_NAME}:${SOURCEDIR}
        - ./${COMMON_DIR_NAME}/event_types.ts:${WORKDIR}/${COMMON_DIR_NAME}/event_types.ts
        - ./${COMMON_DIR_NAME}/db:${WORKDIR}/${COMMON_DIR_NAME}/db
      environment:
        << : [*mssql_env]
      tty: false
      stdin_open: false
      restart: no
      depends_on:
        sqldb:
          condition: service_started

  message_sink:
      extends:
        file: base_services.yaml
        service: node_kafka_app
      hostname: "${MESSAGE_SINK_NAME}"
      volumes:
        - ./${MESSAGE_SINK_NAME}:${SOURCEDIR}
        - ./${COMMON_DIR_NAME}/db:${WORKDIR}/${COMMON_DIR_NAME}/db
      environment:
        << : [*mssql_env]
      # tty: false
      # stdin_open: false
      depends_on:
        kafka1:
          condition: service_started
        sqldb:
          condition: service_healthy

  statement_generator:
      extends:
        file: base_services.yaml
        service: node_monitored_app
      volumes:
        - ./${STATEMENT_GENERATOR_NAME}:${SOURCEDIR}
        - shared_dir:${SHARED_DIR}
        - ./${COMMON_DIR_NAME}/files.ts:${WORKDIR}/${COMMON_DIR_NAME}/files.ts
        - ./${COMMON_DIR_NAME}/db:${WORKDIR}/${COMMON_DIR_NAME}/db
        - ./${COMMON_DIR_NAME}/event_types.ts:${WORKDIR}/${COMMON_DIR_NAME}/event_types.ts
        - ./${COMMON_DIR_NAME}/generator_parameters.ts:${WORKDIR}/${COMMON_DIR_NAME}/generator_parameters.ts
        - ./${COMMON_DIR_NAME}/apiRequestHandler.ts:${WORKDIR}/${COMMON_DIR_NAME}/apiRequestHandler.ts
      hostname: "${STATEMENT_GENERATOR_NAME}"
      environment:
        << : [*mssql_env]
        SHARED_DIR: ${SHARED_DIR}
        STATEMENT_GENERATOR_PORT: ${STATEMENT_GENERATOR_PORT}
      depends_on:
        db_initializer:
          condition: service_completed_successfully
  backend:
    image: busybox
    depends_on:
      gql:
        condition: service_healthy
      db_initializer:
        condition: service_completed_successfully
      message_sink:
        condition: service_healthy
      graphana:
        condition: service_started
      prometheus:
        condition: service_started

  tester:
      extends:
        file: base_services.yaml
        service: node_app
      volumes:
        - ./${TESTER_NAME}:${SOURCEDIR}
        - shared_dir:${SHARED_DIR}
        - ./${COMMON_DIR_NAME}/event_types.ts:${WORKDIR}/${COMMON_DIR_NAME}/event_types.ts
        - ./${COMMON_DIR_NAME}/files.ts:${WORKDIR}/${COMMON_DIR_NAME}/files.ts
        - ./${COMMON_DIR_NAME}/generator_parameters.ts:${WORKDIR}/${COMMON_DIR_NAME}/generator_parameters.ts
        - ./${COMMON_DIR_NAME}/gqlDeclarations.ts:${WORKDIR}/${COMMON_DIR_NAME}/gqlDeclarations.ts
      environment:
        SHARED_DIR: ${SHARED_DIR}
        <<: [*gql_env]
        TESTER_PORT: ${TESTER_PORT}
        TESTER_HOST: ${TESTER_NAME}
      # tty: false
      # stdin_open: false
      restart: no