
volumes:
  build_folder:
    external: true


networks:
  split_hosting_isolated_net:
    name: split_hosting_isolated_net
    driver: bridge
  edge_net:
    driver: bridge
    name: edge_net

services:
  frontend_builder:
      extends:
        file: frontend_builder/compose.yaml
        service: frontend_builder
  nginx_server:
    extends:
      file: ./nginx_server/compose.yaml
      service: nginx_server
    depends_on:
      tunnel:
        condition: service_started
      frontend_builder:
        condition: service_completed_successfully
    networks:
      - split_hosting_isolated_net
      - edge_net
  auth:
    extends:
      file: ./auth/compose.yaml
      service: auth
    depends_on:
      redis:
        condition: service_started
    networks:
      - edge_net
      - split_hosting_isolated_net
  redis:
    extends:
      file: ./auth/compose.yaml
      service: redis
    networks:
      - split_hosting_isolated_net
  tunnel:
    extends:
      file: ./tunnel/compose.yaml
      service: tunnel
    networks:
      - split_hosting_isolated_net
      - edge_net
  
  deploy:
    image: busybox
    depends_on:
      nginx_server:
        condition: service_started
      auth:
        condition: service_healthy
      redis:
        condition: service_started
      tunnel:
        condition: service_started