

networks:
  backend_net1:
    driver: bridge
    name: backend_net1
  edge_net_backend:
    driver: bridge
    name: edge_net_backend

volumes:
  build_folder:
  shared_dir:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1G

services:
  tunnel_client:
    extends:
      file: ./tunnel_client/compose.yaml
      service: tunnel_client
    networks:
      - backend_net1
      - edge_net_backend
    depends_on:
      gql:
        condition: service_healthy

  gql:
    extends:
      file: ./${GQL_APP_NAME}/compose.yaml
      service: ${GQL_APP_NAME}
    networks:
      - backend_net1

  generator:
    extends:
      file: ./generator/compose.yaml
      service: generator
    networks:
      - backend_net1
    depends_on:
      kafka-init:
        condition: service_completed_successfully

  kafka:
    extends:
      file: ./kafka/compose.yaml
      service: kafka
    networks:
      - backend_net1

  kafka-init:
    extends:
      file: ./kafka/compose.yaml
      service: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend_net1

  message_sink:
    extends:
      file: ./${MESSAGE_SINK_NAME}/compose.yaml
      service: ${MESSAGE_SINK_NAME}
    networks:
      - backend_net1
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      db_initializer:
        condition: service_completed_successfully

  sqldb:
    extends:
      file: ./sqldb/compose.yaml
      service: sqldb
    networks:
      - backend_net1
  
  sql_monitor:
    extends:
      file: ./sqldb/compose.yaml
      service: sql_monitor
    networks:
      - backend_net1
    depends_on:
      sqldb:
        condition: service_started

  db_initializer:
    extends:
      file: ./${DB_INITIALIZER_NAME}/compose.yaml
      service: ${DB_INITIALIZER_NAME}
    networks:
      - backend_net1
    depends_on:
      sql_monitor:
        condition: service_healthy

  statement_generator:
    extends:
      file: ./statement_generator/compose.yaml
      service: statement_generator
    networks:
      - backend_net1
    depends_on:
      db_initializer:
        condition: service_completed_successfully

  prometheus:
    extends:
      file: ./prometheus/compose.yaml
      service: prometheus
    networks:
      - backend_net1
  
  grafana:
    extends:
      file: ./grafana/compose.yaml
      service: grafana
    networks:
      - backend_net1
      - edge_net_backend
  
  
  split_host_back:
    image: busybox
    depends_on:
      db_initializer:
        condition: service_completed_successfully
      kafka-init:
        condition: service_completed_successfully
      gql:
        condition: service_healthy
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
      generator:
        condition: service_healthy
      statement_generator:
        condition: service_healthy
      message_sink:
        condition: service_healthy
      tunnel_client:
        condition: service_started