volumes:
  ${FRONTEND_BUILD_FOLDER_VOLUME_NAME}:
    external: true

services:
  nginx_server:
    image: nginx:mainline-alpine3.22
    container_name: nginx_server
    env_file:
      - ../${ALL_VARS_FILE_NAME}
    volumes:
    - ${FRONTEND_DEPLOY_FOLDER_HOST}:${NGINX_FOLDER}
    - ${NGINX_CONF_FILE}:${NGINX_ENVSUBST_TEMPLATE_DIR}/f.conf.template
    - ${LOG_MOUNT_HOST}:${LOG_MOUNT}
    ports:
    - "${NGINX_HOST_ADDR}:${NGINX_PORT}"
