
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./:${SOURCEDIR}
    hostname: "${PROMETHEUS_HOSTNAME}"
    env_file:
      - ../.env
    entrypoint: ["sh", "-c"]
    tty: true
    command: ['${SOURCEDIR}/generateConfig.sh > /etc/prometheus/prometheus.yml;
              prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus;
              exec sh']
