#!/bin/sh

AUTOSSH_GATETIME=0 \
    AUTOSSH_LOGFILE="${WORKDIR}/autossh_logs.log" \
    autossh -M 0 \
    -o StrictHostKeyChecking=no \
    -o ExitOnForwardFailure=yes \
    -o ServerAliveInterval=10 \
    -o ServerAliveCountMax=2 \
    -vv \
    -R $TUNNEL_CLIENT_REMOTE_GQL_PORT:$TUNNEL_CLIENT_LOCAL_GQL_HOST_NAME:$TUNNEL_CLIENT_LOCAL_GQL_PORT \
    -L $TUNNEL_CLIENT_LOCAL_AUTH_MONITORING_PORT:$TUNNEL_CLIENT_REMOTE_AUTH_HOSTNAME:$TUNNEL_CLIENT_REMOTE_AUTH_MONITORING_PORT \
    -N $TUNNEL_CLIENT_SERVER_USER@$TUNNEL_CLIENT_SERVER_ADDR \
    -i ${TUNNEL_CLIENT_MOUNTED_PRIVATE_KEY_NAME} \
    -p $TUNNEL_CLIENT_SERVER_PORT;

echo "activated $?"