services:
 tunnel_client:
    build:
        dockerfile_inline: |
          FROM alpine:latest
          RUN apk update; apk add autossh;
          RUN adduser ${TUNNEL_CLIENT_USER_NAME} -D
    tty: true
    stdin_open: true
    user: ${TUNNEL_CLIENT_USER_NAME}
    hostname: ${TUNNEL_CLIENT_HOST_NAME}
    entrypoint: ["sh", "-c"]
    command: ["sh /activate.sh; exec sh"]
    env_file:
      - ../.env
    volumes:
      - ${TUNNEL_CLIENT_PRIVATE_KEY_TO_MOUNT}:${TUNNEL_CLIENT_MOUNTED_PRIVATE_KEY_NAME}:ro
      - ${TUNNEL_CLIENT_PUBLIC_KEY_TO_MOUNT}:${TUNNEL_CLIENT_MOUNTED_PUBLIC_KEY_NAME}:ro
      - ./activate.sh:/activate.sh:ro