services:
  graphana:
    image: grafana/grafana:11.6.3
    hostname: "${GRAPHANA_HOSTNAME}"
    volumes:
      -  /${GRAPHANA_DASHBOARD_FOLDER}
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dash1.json:/${GRAPHANA_DASHBOARD_FOLDER}/dash1.json
    env_file:
      - ../.env
    tty: true
    stdin_open: true
    ports:
      - "${GRAPHANA_EXPOSED_PORT_ADDR}:${GRAPHANA_PORT}"