services:
  db_initializer:
    extends:
      file: ../base_services.yaml
      service: node_app
    volumes:
      - ./:${WORKDIR}/${DB_INITIALIZER_NAME}
    environment:
      LOCALVAR: ${DB_INITIALIZER_NAME}
    env_file:
      - ../${ALL_VARS_FILE_NAME}
    restart: "no"
    tty: false
    stdin_open: false
